refactor(qrolo.dart): broke context 0 source width, attempt using refactored local
IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

BREAKING CHANGE: This breaks existing functionality. No more scan early errors.